In [20]:
import numpy as np

# Vectors Warmup

In [21]:
x = np.array([0,1,2,3])
print('x = ' + str(x))
y = np.array([4,5,6,7])
print('y = ' + str(y))

x = [0 1 2 3]
y = [4 5 6 7]


In [22]:
# dot product
np.einsum('i,i->', x, y)

38

In [23]:
# outer product
np.einsum("i,j->ij", x, y)

array([[ 0,  0,  0,  0],
       [ 4,  5,  6,  7],
       [ 8, 10, 12, 14],
       [12, 15, 18, 21]])

In [24]:
# compute Hadamard product
np.einsum('i,i -> i', x, y)

array([ 0,  5, 12, 21])

In [25]:
# compute double sum over indices of A and B
np.einsum('i,j ->', x, y)

132

In [26]:
# compute x_i * (y1 + y2 + y3 + y4) for all i 
np.einsum('i,j -> i', x, y)

array([ 0, 22, 44, 66])

In [31]:
# sum all entries in the vector
display(np.einsum('i ->', x))
display(np.einsum('i ->', y))

6

22

In [37]:
# reshape the dimensions of the matrix 
z = np.ones((5,4,3))
np.einsum('ijk -> kji', z).shape

(3, 4, 5)

# Matrices Warmup

In [17]:
C = np.array([[0, 1], [2, 3]])
D = np.array([[4, 5], [6, 7]])
print('C = \n' + str(C))
print('D = \n' + str(D))

C = 
[[0 1]
 [2 3]]
D = 
[[4 5]
 [6 7]]


In [18]:
# compute matrix multiplication 
np.einsum('ij,jk -> ik', C, D)

array([[ 6,  7],
       [26, 31]])

In [19]:
# compute sum of Cij * Dji
np.einsum('ij, ji ->', C, D)

37

# Exercises

In [57]:
A = np.array([[0, 1, 2], [3, 4, 5]])
x = np.array([[1, 2, 3]])
print('A = \n' + str(A))
print('x = \n' + str(x))

A = 
[[0 1 2]
 [3 4 5]]
x = 
[[1 2 3]]


In [58]:
# transpose the matrix
np.einsum('ij -> ji', A)

array([[0, 3],
       [1, 4],
       [2, 5]])

In [59]:
# sum all the elements 
np.einsum('ij ->', A)

15

In [60]:
# column sum of A
np.einsum('ij -> j', A)

array([3, 5, 7])

In [61]:
# row sum of A
np.einsum('ij -> i', A)

array([ 3, 12])

In [66]:
# multiply A with x^T
np.einsum('ij, kj -> ik', A, x)

array([[ 8],
       [26]])

In [71]:
# multiply A with A^T
np.einsum('ij, kj -> ik', A, A)

# A @ A.transpose()

array([[ 5, 14],
       [14, 50]])

In [72]:
# dot product first row with first row of matrix 
np.einsum('i,i', A[0], A[0])

5

In [79]:
# dot product with matrix 
display(np.einsum('ij, ij->', A, A))

np.einsum('ij, ij->', A, A) == (np.linalg.norm(A, ord = 'fro'))**2

55

True

In [83]:
# outer product
a = np.array([1,2,3])
b = np.array([4,5,6,7])
np.einsum('i,j -> ij', a, b)

array([[ 4,  5,  6,  7],
       [ 8, 10, 12, 14],
       [12, 15, 18, 21]])

In [87]:
# Batch Matrix Multiplication
a = np.random.rand(3,2,5)
b = np.random.rand(3,5,3)
np.einsum('ijk, ikl-> ijl', a, b)

array([[[2.50021717, 1.99245007, 1.59014343],
        [1.49386101, 1.17066172, 0.8330688 ]],

       [[1.37229032, 1.74985941, 1.23733016],
        [1.36897924, 1.84563394, 1.19644313]],

       [[1.03043444, 2.3159234 , 1.71590156],
        [0.38810691, 0.98205419, 0.7159932 ]]])

In [90]:
# Matrix Diagonal 
c = np.random.rand(3,3)
np.einsum('ii -> i', c)

array([0.56823804, 0.30348305, 0.68553907])

In [91]:
# Matrix Trace
np.einsum('ii ->', c)

1.5572601602162233

# Exercises from ROCKTÄSCHEL

In [102]:
# matrix transpose
a = np.arange(6).reshape(2, 3)
display(a)
np.einsum('ij->ji', a)

array([[0, 1, 2],
       [3, 4, 5]])

array([[0, 3],
       [1, 4],
       [2, 5]])

In [103]:
np.einsum('ij->', a)

15

In [3]:
import numpy as np

In [12]:
np.ones(2**34)

array([1., 1., 1., ..., 1., 1., 1.])

In [13]:
2**34

17179869184

In [14]:
2**100

1267650600228229401496703205376