In [3]:
from qutip import *
import numpy as np

In [4]:
a = create(5)
a

Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = False
Qobj data =
[[0.         0.         0.         0.         0.        ]
 [1.         0.         0.         0.         0.        ]
 [0.         1.41421356 0.         0.         0.        ]
 [0.         0.         1.73205081 0.         0.        ]
 [0.         0.         0.         2.         0.        ]]

In [5]:
tensor(sigmax(), identity(2))

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]

In [6]:
tensor([a.dag(),identity(2),a,identity(2)])

Quantum object: dims = [[5, 2, 5, 2], [5, 2, 5, 2]], shape = (100, 100), type = oper, isherm = False
Qobj data =
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

In [7]:
### ZZ gate

theta = np.random.rand()
alpha = np.sqrt(theta/4)
U1 = tensor(Dc(-alpha,alpha),I2)
U2 = tensor(Dc(1j*alpha,-1j*alpha),I2).permute([0,2,1])

U = U2.dag()*U1.dag()*U2*U1

P = tensor(basis(cutoff,0).dag(),I2,I2)
P*U*P.dag() == (-1j*theta*tensor(sigmaz(),sigmaz())/2).expm()

NameError: name 'Dc' is not defined

In [228]:
### CNOT
alpha = np.sqrt(np.pi/2)
U1 = tensor([DCZ(alpha),I2])
U2 = tensor([DCX(1j*alpha),I2]).permute([0,2,1])

U = (U2.dag()*U1.dag()*U2*U1)

In [229]:
P = tensor(basis(cutoff,0).dag(),I2,I2)
P*U*P.dag()

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[1.00000000e+00+0.00000000e+00j 0.00000000e+00+0.00000000e+00j
  0.00000000e+00+0.00000000e+00j 0.00000000e+00+0.00000000e+00j]
 [0.00000000e+00+0.00000000e+00j 1.00000000e+00+0.00000000e+00j
  0.00000000e+00+0.00000000e+00j 0.00000000e+00+0.00000000e+00j]
 [0.00000000e+00+0.00000000e+00j 0.00000000e+00+0.00000000e+00j
  2.28454914e-11+8.34122905e-11j 1.00000000e+00-8.34121794e-11j]
 [0.00000000e+00+0.00000000e+00j 0.00000000e+00+0.00000000e+00j
  1.00000000e+00-8.34121683e-11j 2.28453919e-11+8.34121564e-11j]]

In [230]:
### Toffoli
alpha = np.sqrt(np.pi/2)
cp = tensor(CP(),I2).permute([0,2,1])
d1 = tensor([Dc(0,-1j*alpha/2),I2])
d2 = tensor([Dc(0,alpha/2),I2])

U12 = tensor([d2*cp*d1*cp.dag(),I2])

U3 = tensor([DCX(1j*alpha),I2,I2]).permute([0,3,2,1])

Utoff = U3.dag()*U12.dag()*U3*U12

In [231]:
P = tensor(basis(cutoff,0).dag(),I2,I2,I2)
P*Utoff*P.dag()

Quantum object: dims = [[2, 2, 2], [2, 2, 2]], shape = (8, 8), type = oper, isherm = False
Qobj data =
[[1.00000000e+00+0.00000000e+00j 0.00000000e+00+0.00000000e+00j
  0.00000000e+00+0.00000000e+00j 0.00000000e+00+0.00000000e+00j
  0.00000000e+00+0.00000000e+00j 0.00000000e+00+0.00000000e+00j
  0.00000000e+00+0.00000000e+00j 0.00000000e+00+0.00000000e+00j]
 [0.00000000e+00+0.00000000e+00j 1.00000000e+00+0.00000000e+00j
  0.00000000e+00+0.00000000e+00j 0.00000000e+00+0.00000000e+00j
  0.00000000e+00+0.00000000e+00j 0.00000000e+00+0.00000000e+00j
  0.00000000e+00+0.00000000e+00j 0.00000000e+00+0.00000000e+00j]
 [0.00000000e+00+0.00000000e+00j 0.00000000e+00+0.00000000e+00j
  1.00000000e+00+0.00000000e+00j 0.00000000e+00+0.00000000e+00j
  0.00000000e+00+0.00000000e+00j 0.00000000e+00+0.00000000e+00j
  0.00000000e+00+0.00000000e+00j 0.00000000e+00+0.00000000e+00j]
 [0.00000000e+00+0.00000000e+00j 0.00000000e+00+0.00000000e+00j
  0.00000000e+00+0.00000000e+00j 1.00000000e+00+0.00000000e+00

In [282]:
## ZZ parallel

theta = np.random.rand()
alpha = np.sqrt(theta/4)/np.sqrt(2)

term1  = tensor(Dc(-alpha,alpha),Dc(-alpha,alpha))
term2 = BS(np.pi,-np.pi/2).dag()*tensor(Dc(-1j*alpha,1j*alpha),Dc(1j*alpha,-1j*alpha))*BS(np.pi,-np.pi/2)

# term1  = tensor([Dc(-alpha,alpha),Ib,I2])
# term2 = BS(np.pi,-np.pi/2).dag()*tensor([Ib,I2,Dc(1j*alpha,-1j*alpha)])*BS(np.pi,-np.pi/2)

U = term2.dag()*term1.dag()*term2*term1

In [283]:
P = tensor(basis(cutoff,0).dag(),I2,basis(cutoff,0).dag(),I2)
P*U*P.dag()

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[0.99360344-0.11292565j 0.        +0.j         0.        +0.j
  0.        +0.j        ]
 [0.        +0.j         0.99360344+0.11292565j 0.        +0.j
  0.        +0.j        ]
 [0.        +0.j         0.        +0.j         0.99360344+0.11292565j
  0.        +0.j        ]
 [0.        +0.j         0.        +0.j         0.        +0.j
  0.99360344-0.11292565j]]

In [285]:
P*U*P.dag() == (-1j*theta*tensor(sigmaz(),sigmaz())/2).expm()

True