In [6]:
from qutip import *
import numpy as np

In [20]:
cutoff = 20

a = destroy(cutoff)
I2 = identity(2)
Ib = identity(cutoff)

def BS(theta,phi):
    term = tensor([a.dag(),identity(2),a,identity(2)])
    phase = np.exp(1j*phi)
    return (-1j*(theta/2)*(phase*term + np.conj(phase)*term.dag())).expm()

def D(alpha):
    return (alpha*a.dag() - np.conj(alpha)*a).expm()

def Dc(alpha, beta):
    return tensor(D(alpha), basis(2,0)*basis(2,0).dag()) + tensor(D(beta), basis(2,1)*basis(2,1).dag())
    
def CP():
    return (-1j*(np.pi/2)*tensor(a.dag()*a,sigmaz())).expm()

def DCX(alpha):
    return tensor(alpha*a.dag() - np.conj(alpha)*a, (I2 - sigmax())/2).expm()

def DCZ(alpha):
    return tensor(alpha*a.dag() - np.conj(alpha)*a, (I2 - sigmaz())/2).expm()
    

In [24]:
DCZ(α) == Dc(0, α)

True

In [21]:
### ZZ gate

theta = np.random.rand()
alpha = np.sqrt(theta/4)
U1 = tensor(Dc(-alpha,alpha),I2)
U2 = tensor(Dc(1j*alpha,-1j*alpha),I2).permute([0,2,1])

U = U2.dag()*U1.dag()*U2*U1

P = tensor(basis(cutoff,0).dag(),I2,I2)
P*U*P.dag() == (-1j*theta*tensor(sigmaz(),sigmaz())/2).expm()

True

In [25]:
### CNOT
alpha = np.sqrt(np.pi/2)
U1 = tensor([DCZ(alpha),I2])
U2 = tensor([DCX(1j*alpha),I2]).permute([0,2,1])

U = (U2.dag()*U1.dag()*U2*U1)

In [26]:
P = tensor(basis(cutoff,0).dag(),I2,I2)
P*U*P.dag()

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[1.00000000e+00+0.00000000e+00j 0.00000000e+00+0.00000000e+00j
  0.00000000e+00+0.00000000e+00j 0.00000000e+00+0.00000000e+00j]
 [0.00000000e+00+0.00000000e+00j 1.00000000e+00+0.00000000e+00j
  0.00000000e+00+0.00000000e+00j 0.00000000e+00+0.00000000e+00j]
 [0.00000000e+00+0.00000000e+00j 0.00000000e+00+0.00000000e+00j
  2.28456259e-11+8.34121713e-11j 1.00000000e+00-8.34120941e-11j]
 [0.00000000e+00+0.00000000e+00j 0.00000000e+00+0.00000000e+00j
  1.00000000e+00-8.34121242e-11j 2.28454823e-11+8.34121092e-11j]]

In [11]:
### Toffoli
alpha = np.sqrt(np.pi/2)
cp = tensor(CP(),I2).permute([0,2,1])
d1 = tensor([Dc(0,-1j*alpha/2),I2])
d2 = tensor([Dc(0,alpha/2),I2])

U12 = tensor([d2*cp*d1*cp.dag(),I2])

U3 = tensor([DCX(1j*alpha),I2,I2]).permute([0,3,2,1])

Utoff = U3.dag()*U12.dag()*U3*U12

In [12]:
P = tensor(basis(cutoff,0).dag(),I2,I2,I2)
P*Utoff*P.dag()

Quantum object: dims = [[2, 2, 2], [2, 2, 2]], shape = (8, 8), type = oper, isherm = False
Qobj data =
[[1.00000000e+00+0.00000000e+00j 0.00000000e+00+0.00000000e+00j
  0.00000000e+00+0.00000000e+00j 0.00000000e+00+0.00000000e+00j
  0.00000000e+00+0.00000000e+00j 0.00000000e+00+0.00000000e+00j
  0.00000000e+00+0.00000000e+00j 0.00000000e+00+0.00000000e+00j]
 [0.00000000e+00+0.00000000e+00j 1.00000000e+00+0.00000000e+00j
  0.00000000e+00+0.00000000e+00j 0.00000000e+00+0.00000000e+00j
  0.00000000e+00+0.00000000e+00j 0.00000000e+00+0.00000000e+00j
  0.00000000e+00+0.00000000e+00j 0.00000000e+00+0.00000000e+00j]
 [0.00000000e+00+0.00000000e+00j 0.00000000e+00+0.00000000e+00j
  1.00000000e+00+0.00000000e+00j 0.00000000e+00+0.00000000e+00j
  0.00000000e+00+0.00000000e+00j 0.00000000e+00+0.00000000e+00j
  0.00000000e+00+0.00000000e+00j 0.00000000e+00+0.00000000e+00j]
 [0.00000000e+00+0.00000000e+00j 0.00000000e+00+0.00000000e+00j
  0.00000000e+00+0.00000000e+00j 1.00000000e+00+0.00000000e+00

In [13]:
## ZZ parallel

theta = np.random.rand()
alpha = np.sqrt(theta/4)/np.sqrt(2)

term1  = tensor(Dc(-alpha,alpha),Dc(-alpha,alpha))
term2 = BS(np.pi,-np.pi/2).dag()*tensor(Dc(-1j*alpha,1j*alpha),Dc(1j*alpha,-1j*alpha))*BS(np.pi,-np.pi/2)

# term1  = tensor([Dc(-alpha,alpha),Ib,I2])
# term2 = BS(np.pi,-np.pi/2).dag()*tensor([Ib,I2,Dc(1j*alpha,-1j*alpha)])*BS(np.pi,-np.pi/2)

U = term2.dag()*term1.dag()*term2*term1

In [14]:
P = tensor(basis(cutoff,0).dag(),I2,basis(cutoff,0).dag(),I2)
P*U*P.dag()

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[0.88126827-0.47261636j 0.        +0.j         0.        +0.j
  0.        +0.j        ]
 [0.        +0.j         0.88126827+0.47261636j 0.        +0.j
  0.        +0.j        ]
 [0.        +0.j         0.        +0.j         0.88126827+0.47261636j
  0.        +0.j        ]
 [0.        +0.j         0.        +0.j         0.        +0.j
  0.88126827-0.47261636j]]

In [15]:
P*U*P.dag() == (-1j*theta*tensor(sigmaz(),sigmaz())/2).expm()

True

In [17]:
## CNOT parallel
π = np.pi
α = np.sqrt(π/4)#/np.sqrt(2)

H = Qobj([[1,1],[1,-1]],dims=[[2],[2]])/np.sqrt(2)

term1  = tensor(Dc(0,α),Dc(0,α))
term2 = BS(π,π/2)*tensor(Dc(0,1j*α),Dc(0,-1j*α))*BS(π,-π/2)
term3  = tensor(Dc(0,-α),Dc(0,-α))
term4 = BS(π,π/2)*tensor(Dc(0,-1j*α),Dc(0,1j*α))*BS(π,-π/2)

# α = np.sqrt(theta/2)
# term1  = tensor([Dc(0,α),Ib,I2])
# term2 = BS(π,π/2)*tensor([Ib,I2,Dc(0,-1j*α)])*BS(π,-π/2)
# term3  = tensor([Dc(0,-α),Ib,I2])
# term4 = BS(π,π/2)*tensor([Ib,I2,Dc(0,1j*α)])*BS(π,-π/2)

# U = tensor(Ib,I2,Ib,H)*term2.dag()*term1.dag()*term2*term1*tensor(Ib,I2,Ib,H)
U = tensor(Ib,I2,Ib,H)*term4*term3*term2*term1*tensor(Ib,I2,Ib,H)

P = tensor(basis(cutoff,0),I2,basis(cutoff,0),I2)
P.dag()*U*P

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[1.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.16613996e-10 1.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00 1.16613996e-10]]

In [69]:
(1j*(np.pi/2)*tensor((I2-sigmaz())/2,(I2-sigmax())/2)).expm()


Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[1. +0.j  0. +0.j  0. +0.j  0. +0.j ]
 [0. +0.j  1. +0.j  0. +0.j  0. +0.j ]
 [0. +0.j  0. +0.j  0.5+0.5j 0.5-0.5j]
 [0. +0.j  0. +0.j  0.5-0.5j 0.5+0.5j]]

In [70]:
U.dag()*tensor(sigmax(),I2)*U

TypeError: Incompatible Qobj shapes

In [ ]:
tensor(sigmax(),sigmax())

In [ ]:
BS(np.pi,-np.pi/2).dag() == BS(np.pi,np.pi/2)

In [71]:
## XX+ZZ parallel

theta = np.pi/2
alpha = np.sqrt(theta/4)/np.sqrt(2)

H = Qobj([[1,1],[1,-1]],dims=[[2],[2]])/np.sqrt(2)

term1  = tensor(Ib,I2,Ib,H)*tensor(Dc(-alpha,alpha),Dc(-alpha,alpha))*tensor(Ib,I2,Ib,H)
term2 = tensor(Ib,I2,Ib,H)*BS(np.pi,np.pi/2)*tensor(Dc(-1j*alpha,1j*alpha),Dc(1j*alpha,-1j*alpha))*BS(np.pi,-np.pi/2)*tensor(Ib,I2,Ib,H)
# term3  = tensor(Ib,I2,Ib,H)*tensor(Dc(alpha,-alpha),Dc(alpha,-alpha))*tensor(Ib,I2,Ib,H)
# term4 = tensor(Ib,H,Ib,I2)*BS(np.pi,np.pi/2)*tensor(Dc(1j*alpha,-1j*alpha),Dc(-1j*alpha,1j*alpha))*BS(np.pi,-np.pi/2)*tensor(Ib,H,Ib,I2)

# term1  = tensor(Dc(-alpha,alpha),Dc(-alpha,alpha))
# term2 = BS(np.pi,np.pi/2)*tensor(Dc(-1j*alpha,1j*alpha),Dc(1j*alpha,-1j*alpha))*BS(np.pi,-np.pi/2)
# term3  = tensor(Dc(alpha,-alpha),Dc(alpha,-alpha))
# term4 = BS(np.pi,np.pi/2)*tensor(Dc(1j*alpha,-1j*alpha),Dc(-1j*alpha,1j*alpha))*BS(np.pi,-np.pi/2)

# U = tensor(Ib,I2,Ib,H)*term2.dag()*term1.dag()*term2*term1*tensor(Ib,I2,Ib,H)
U = term2.dag()*term1.dag()*term2*term1

In [72]:
P = tensor(basis(cutoff,0).dag(),I2,basis(cutoff,0).dag(),I2)
P*U*P.dag()

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[0.70710678+0.j         0.        -0.70710678j 0.        +0.j
  0.        +0.j        ]
 [0.        -0.70710678j 0.70710678+0.j         0.        +0.j
  0.        +0.j        ]
 [0.        +0.j         0.        +0.j         0.70710678+0.j
  0.        +0.70710678j]
 [0.        +0.j         0.        +0.j         0.        +0.70710678j
  0.70710678+0.j        ]]

In [73]:
(-1j*(theta/2)*(tensor(sigmaz(),sigmaz()) + tensor(sigmax(),sigmax()))).expm()

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[ 0.5-0.5j  0. +0.j   0. +0.j  -0.5-0.5j]
 [ 0. +0.j   0.5+0.5j  0.5-0.5j  0. +0.j ]
 [ 0. +0.j   0.5-0.5j  0.5+0.5j  0. +0.j ]
 [-0.5-0.5j  0. +0.j   0. +0.j   0.5-0.5j]]

In [74]:
np.arctan(0.132/0.932)/np.pi

0.04478465148727872

In [75]:
np.sqrt(1/5)

0.4472135954999579

In [76]:
Util = P*U*P.dag()

In [77]:
Util.dag()*Util

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]